coverage:
  status:
    project:
      default:
        target: auto
    patch: off
    changes: off
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
  branches:
    - master
